export enum PointTransactionType {
  BINARY_COMMISSION = 'BINARY_COMMISSION',
  DIRECT_BONUS = 'DIRECT_BONUS',
  WITHDRAWAL = 'WITHDRAWAL',
  PAYMENT_DEDUCTION = 'PAYMENT_DEDUCTION',
  RECONSUMPTION_ORDER = 'RECONSUMPTION_ORDER',
  RECONSUMPTION_POINTS = 'RECONSUMPTION_POINTS',
}
